import Footer from '@/components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'
import { GlobalContextProvider } from '@/context/useContext'

export const metadata: Metadata = {
  title: 'Innova XI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <GlobalContextProvider>
          <Navbar />{children}<Footer />
        </GlobalContextProvider>
      </body>
    </html>
  )
}
