import Footer from '@/components/Footer'//learn@
import './globals.css'//learn why without var
import type { Metadata } from 'next'//why type
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'Innova XI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode //
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
